site_name: Knowledgedatabase
theme:
  name: material
  palette: 
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Basics:
    - Certificates: basics/certs.md
    - Regular Expressions: basics/regex.de
  - Linux:
    - Basic Commands: linux/basic_commands.md
    - Storage Stack: linux/storage_stack.md
  - Powershell: powershell.md