site_name: Knowledgedatabase
theme:
  name: material
  palette: 
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Basics:
    - Git: basics/git.md
    - Certificates: basics/certs.md
    - Regular Expressions: basics/regex.md
    - Firewall: basics/firewall.md
    - Network: basics/networking.md
  - Ansible:
    - Basics: ansible/ansible_basics.md
    - Inventory: ansible/ansible_inventory.md
    - Roles: ansible/ansible_roles.md
    - Variables: ansible/ansible_variables.md
    - Vault: ansible/ansible_vault.md
    - Ansible Lint: ansible/ansible_lint.md
    - Execution Environments: ansible/ansible_execution_environments.md
    - Writing Extensions: ansible/ansible_writing_extensions.md
    - Molecule: ansible/ansible_molecule.md
  - Linux:
    - Basic Commands: linux/basic_commands.md
    - Storage Stack: linux/storage_stack.md
    - RHEL System Administration: linux/rhel_system_administration.md
  - Powershell: powershell.md